#!/bin/bash
# @author:'jakimfett'
# @license;'cc-by-sa'
#
# Automate microsite publication and caching.


cd microsite

# These options wipe out the branch each time.
# git rm -r --cached .
# git clean -fxd
# git branch -D gh-pages
# git checkout --orphan gh-pages
#git fetch origin development
#git show development:functions.sh > index.html
cat ../functions.sh > index.html
git add index.html
cat index.html | sha3sum | awk '{print $1}' > sha3.hash
cat index.html | md5sum | awk '{print $1}' > md5.hash
git add *.hash
#git commit -m "autogenerated by prototype"
