#!/bin/bash
# @author:'jakimfett'
# @license;'cc-by-sa'
#
# Automate microsite publication and caching.


cd microsite
git branch -D gh-pages
git checkout --orphan gh-pages
git show development:functions.sh > index.html
git rm -r --cached .
git add index.html
git commit -m "autogenerated by prototype"
git clean -fxd
